import type { HomePage, SiteSettings } from "@/types/content";

export const fallbackSettings: SiteSettings = {
  title: "Axis & Sage",
  brandDescription: "Strategy, design, growth, venture building and storytelling.",
  defaultCta: { label: "Work with us", href: "#contact" },
  navigation: [
    { label: "About", href: "#about" },
    { label: "Services", href: "#services" },
    { label: "Our work", href: "#our-work" },
    { label: "FAQs", href: "#faqs" },
    { label: "Contact", href: "#contact" },
  ],
  footerNavigation: [
    { label: "About us", href: "#about" },
    { label: "Our work", href: "#our-work" },
    { label: "Services", href: "#services" },
    { label: "FAQs", href: "#faqs" },
    { label: "Contact", href: "#contact" },
  ],
  contactEmail: "info@axisandsage.com",
  officeLocations: ["Abu Dhabi, Dubai, UAE"],
  socialLinks: [],
  copyright: "",
  seo: {
    title: "Axis and Sage Advisory",
    description: "Axis & Sage Advisory is a boutique strategy, product, and growth partner fusing deep African market insight with GCC execution muscle to help innovators, investors, and public-sector leaders design, build, and scale high-impact ventures.",
  },
};

export const fallbackHome: HomePage = {
  title: "Homepage",
  hero: {
    eyebrow: ["Strategy", "Design", "Growth"],
    heading: "We build businesses, brands, and products that matter",
    body: "A boutique consultancy fusing deep African insight with GCC know-how to help innovators, investors, & public-sector leaders design, build, & scale high-impact ventures.",
    primaryCta: { label: "Work with us", href: "#contact" },
    media: { src: "/images/axis-sage/hero-chess.jpg", alt: "Chess pieces on a board" },
  },
  about: {
    label: "About us",
    heading: "Where strategy meets storytelling",
    body: "At Axis and Sage, we believe every great business starts with a compelling story. We're the strategic architects and creative storytellers who help ambitious leaders build ventures that don't just succeed—they inspire.",
    approach: "Our approach is simple: think strategically, act creatively, grow sustainably.",
    support: [
      "We've helped launch groundbreaking ventures, transform established brands, and connect investors with game-changing opportunities across Africa and beyond.",
      "From product design to market strategy, from storytelling to growth hacking—we're the partners who see your vision and make it reality.",
    ],
    images: ["about-1.jpg", "about-2.jpg", "about-3.jpg", "about-4.jpg", "about-5.jpg", "about-6.jpg"].map((name) => ({ src: `/images/axis-sage/${name}`, alt: "Axis & Sage editorial image" })),
  },
  services: {
    label: "Services",
    heading: "What we do",
    introduction: "Think of us as your strategic Swiss Army knife - versatile, reliable, and always sharp.",
    items: [
      { title: "Strategy", slug: "strategy", summary: "From market research to business model design, we help you navigate complexity and find your true north.", capabilities: ["Market Analysis", "Business Model Design", "Competitive Intelligence", "Growth Planning"], featured: true, detailApproved: true },
      { title: "Design", slug: "design", summary: "We turn complex ideas into clear, compelling brands and products that people want to use.", capabilities: ["Brand Strategy", "Visual Identity", "Product Design", "UX/UI"], featured: true, detailApproved: false },
      { title: "Growth", slug: "growth", summary: "We help ambitious teams find the right audience, sharpen their offer and build momentum that lasts.", capabilities: ["Go-to-Market Strategy", "Growth Systems", "Audience Development", "Partnerships"], featured: true, detailApproved: false },
      { title: "Venture Building", slug: "venture-building", summary: "We work alongside founders and institutions to move promising ideas from opportunity to execution.", capabilities: ["Venture Strategy", "Product Development", "Operating Models", "Investment Readiness"], featured: true, detailApproved: false },
      { title: "Storytelling", slug: "storytelling", summary: "We find the stories that make ventures matter and give them the clarity to travel across audiences.", capabilities: ["Narrative Strategy", "Campaigns", "Content Systems", "Events"], featured: true, detailApproved: false },
    ],
  },
  projects: {
    label: "Our work",
    heading: "Get inspired by our work",
    introduction: "From disruptive startups to established organizations, we've helped ambitious leaders across Africa and beyond achieve remarkable results.",
    items: [
      {
        title: "Nature Roots",
        slug: "nature-roots",
        summary: "We crafted a brand strategy and digital identity that positioned Nature Roots as more than an organic commodities brand — but a trusted link between African farmers and sustainable global markets. From packaging systems to digital presence, our work emphasized transparency, credibility, and scalability, enabling Nature Roots to enter retail channels with confidence.",
        tags: ["Strategy", "Branding"],
        testimonial: { quote: "Axis & Sage’s work was quick, high quality, and completely transformed our brand, making it both beautiful and highly functional.", personName: "Kunmi Demuren", approved: false },
        tone: "sage",
        featured: true,
      },
      {
        title: "Earlybean",
        slug: "earlybean",
        summary: "Axis & Sage partnered with Earlybean to translate a revolutionary savings model into an intuitive digital product for young Africans. From user research with first-time savers to end-to-end UX design, we built a platform that demystifies finance and encourages long-term wealth creation. The outcome: a 10K+ user community within months and strong investor confidence in the model.",
        tags: ["Product Design", "UX/UI"],
        testimonial: { quote: "Incredible work and turnaround times. We went from just an idea to a fully-fledged product with 10K+ active users in no time.", personName: "Biobele Oyibo", approved: false },
        tone: "amber",
        featured: true,
      },
      {
        title: "Uganda Investor Summit",
        slug: "uganda-investor-summit",
        summary: "We delivered end-to-end event strategy, branding, and investor relations for Uganda’s premier investment conference. From stakeholder mapping to compelling event storytelling and visual identity, our team ensured the Summit positioned Uganda as a forward-thinking hub for regional capital flows.",
        tags: ["Event Strategy", "Storytelling"],
        testimonial: { quote: "The quality of work was excellent, and the team was incredibly professional from start to finish.", personName: "Bunmi Akinyemiju", approved: false },
        tone: "ink",
        featured: true,
      },
    ],
  },
  faqs: {
    label: "FAQs",
    heading: "Answering your questions",
    introduction: "Got more questions? Send us your enquiry below",
    cta: { label: "Get in touch", href: "#contact" },
    items: [
      { question: "What exactly does Axis & Sage do?", answer: "We partner with ambitious organizations and founders to design clarity, scale impact, and build trusted brands. Our work sits at the intersection of strategy, brand, product, and storytelling — helping businesses move from idea to execution, and from execution to sustainable growth.", display: true },
      { question: "What area are you based in?", answer: "We work out of our primary offices in Dubai and Abu Dhabi in the UAE, but depending on the project, we are happy to travel to immerse ourselves in our clients problems. Get in touch to discuss your location and project needs.", display: true },
      { question: "Who do you typically work with?", answer: "We work with a diverse range of clients, from early-stage startups validating product-market fit, to growth-stage companies needing sharper strategy and design systems, to public institutions and development partners looking to communicate innovation with credibility. If you’re solving an important problem in Africa or emerging markets — or building bridges between Africa and the world — you’re our kind of client.", display: true },
      { question: "How do you structure engagements?", answer: "Every engagement starts with discovery and alignment — understanding your context, goals, and constraints. From there, we co-design the right format: Sprints (1-3 weeks) for targeted challenges; Projects (4-12 weeks) for broader initiatives; and Partnerships for ongoing design and strategy capacity.", display: true },
      { question: "What makes Axis & Sage different?", answer: "We’re not just an agency chasing pretty outputs, and we’re not consultants delivering slides no one uses. We live at the crossroads of strategy and craft. Our work is pragmatic, fast, and designed to create measurable business impact. Clients say we’re their thought partner and execution arm rolled into one.", display: true },
      { question: "How do you measure success?", answer: "We measure success by the clarity, traction, and trust our clients gain. Sometimes that looks like a startup closing their seed round after we redesign their story, an event attracting more investors and partners than anticipated, or a consumer brand scaling from farmers’ markets to international retail.", display: true },
      { question: "Do you only work in Africa?", answer: "Africa is our heartland — it’s where we’ve honed our craft and built deep understanding. But we also partner with clients in the GCC, Europe, and North America, especially where there’s an Africa connection (diaspora, trade, capital, or cultural).", display: true },
      { question: "What does working with you cost?", answer: "We price based on scope and intensity rather than arbitrary hourly billing. Small sprints may start at a few thousand dollars, while large strategic engagements or long-term advisory partnerships are priced accordingly. The best way to get an accurate sense is to start with a discovery call.", display: true },
      { question: "How can we get started?", answer: "Simple: book a conversation with us. In 30 minutes we’ll unpack your goals, challenges, and opportunities — and if we’re the right fit, we’ll map out an engagement that works.", display: true },
    ],
  },
  contact: {
    label: "Contact",
    heading: "Get in touch",
    introduction: "Got a big idea? A complex challenge? Or just want to explore how we can help? We'd love to hear from you!",
    offices: ["Abu Dhabi, Dubai, UAE"],
    email: "info@axisandsage.com",
  },
  testimonials: {
    label: "Testimonials",
    heading: "Hear from our clients",
    introduction: "Hear from our happy clients about their experience working with Axis & Sage.",
    items: [
      { quote: "Tomiwa helped sharpen our identity. The clarity, speed, and creativity meant that our brand matched our ambitions and spoke to investors, farmers, and customers alike.", personName: "Onyeka Akumah", portrait: { src: "/images/axis-sage/portraits/portrait-2.png", alt: "Onyeka Akumah" }, approved: true },
      { quote: "Axis & Sage has been a thought partner in the truest sense. They see beyond design into the heart of business strategy — aligning brand, structure, and execution seamlessly.", personName: "Bunmi Akinyemiju", portrait: { src: "/images/axis-sage/portraits/portrait-1.jpg", alt: "Bunmi Akinyemiju" }, approved: true },
      { quote: "Their ability to capture the cultural roots and global ambitions of our brand gave us an identity we’re proud to put on shelves anywhere in the world.", personName: "Dinma Obidiebube", portrait: { src: "/images/axis-sage/portraits/portrait-3.jpeg", alt: "Dinma Obidiebube" }, approved: true },
      { quote: "They gave our visual identity clarity that helped us communicate innovation to both public stakeholders and private partners.", personName: "LASRIC (Lagos State Science Research & Innovation Council)", portrait: { src: "/images/axis-sage/portraits/portrait-4.png", alt: "LASRIC" }, approved: true },
      { quote: "They marry strategic depth with creative brilliance. Every engagement with them moves both our thinking and our execution forward.", personName: "Chuks Okeibunor", portrait: { src: "/images/axis-sage/portraits/portrait-5.jpeg", alt: "Chuks Okeibunor" }, approved: true },
      { quote: "Their frameworks for brand and product positioning have consistently given our portfolio companies the edge in competitive markets.", personName: "Temi Olateru", portrait: { src: "/images/axis-sage/portraits/portrait-6.jpg", alt: "Temi Olateru" }, approved: true },
    ],
  },
};
